version: 2.1
jobs:
  home_feature_tests:
    working_directory: ~/code
    docker:
      - image: cimg/android:2023.05
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run all local tests tests
          command: ./gradlew testAppFeature -PfeatureName=home --no-daemon --max-workers=2
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: features/home/presentation/build/test-results
  news_feature_tests:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run all local tests tests
          command: ./gradlew testAppFeature -PfeatureName=news --no-daemon --max-workers=2
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: features/news/presentation/build/test-results
      - store_test_results:
          path: features/news/application/build/test-results
      - store_test_results:
          path: features/news/data/build/test-results
      - store_test_results:
          path: features/news/featureTesting/build/test-results
  e2e_tests:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Build debug APK and release APK
          command: ./gradlew :app:assembleDebug :app:assembleDebugAndroidTest --no-daemon --max-workers=2 --stacktrace
      - run:
          name: Store Google Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run:
          name: Authorize gcloud and set config defaults
          command: |
            sudo gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            sudo gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run:
          name: Test with Firebase Test Lab
          command: >
            sudo gcloud firebase test android run \
              --type instrumentation \
              --app app/build/outputs/apk/debug/app-debug.apk \
              --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
              --device model=redfin,version=30,locale=en,orientation=portrait \
              --use-orchestrator
workflows:
  version: 2
  build_and_test:
    jobs:
      - home_feature_tests
      - news_feature_tests
      - e2e_tests:
          filters:
            branches:
              only: master